### ISSUE TITLE
Bug: rotation of components

### ISSUE THREAD

**Issue by ArticCynda** [JurgenVandendriessche/PickAndPlaceProject#6]
There seems to be a bug in the rotation of components. In [this design](https://circuitmaker.com/Projects/Details/Yannick-Verbelen/16-Bit-8-Channel-DAQ-Shield), 3 identical TVS diodes in SOT363 package were placed (D1, D2 and D3). The first 2 were placed correctly, but D3 is rotated 180°, causing it to short the power rail. Problem was observed on all boards, so it's a machine error and not a random deviation.
Could there be a bug in the code that rotates components, mixing up clockwise and counter clockwise?

**Comment by JurgenVandendriessche** [comment]
Yes this was a bug, it is fixed

**Comment by ArticCynda** [comment]
Glad it's fixed! It was quite a cumbersome task to desolder the diodes manually from **all** the boards!
